FROM node:20-alpine AS builder


WORKDIR /app


ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL
ENV NODE_ENV=production


COPY package*.json ./

RUN npm install --legacy-peer-deps


COPY . .

RUN npm run build

# ---- Étape 2: La "Production" ----
FROM nginx:1.29.1-alpine-slim


LABEL maintainer="Zo <zomahefaranaivo@gmail.com>" \
      description="frontend react pour l'appli de gestion de panne avec django comme back"



COPY --from=builder /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80


RUN apk --no-cache add curl

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD curl -f http://localhost/ || exit 1


