services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - panne_jirama
    

  backend:
    image: zomahefaranaivo/django-app-prod:v1.0
    container_name: django-prod-panne
    restart: always
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - media_data:/back/media
    depends_on:
      - db
    networks:
      - panne_jirama


  frontend:
    image: zomahefaranaivo/react-app-prod:v1.0
    container_name: react-prod-panne
    restart: always
    ports:
      - 3000:80
    depends_on:
      - backend
    networks:
      - panne_jirama


volumes:
  mysql_data:
  media_data:
networks:
  panne_jirama: