services:
  backend-blue:
    image: zomahefaranaivo/django-backend-panne-prod:latest
    container_name: backendBlue
    restart: always
    environment:
      APP_ENV: ${APP_ENV}
      DEBUG: ${DEBUG}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    volumes:
      - django_static:/back/staticfiles
      - django_media:/back/media
    networks:
      - panne-jirama-blue
  frontend-blue:
    image: zomahefaranaivo/react-frontend-panne-prod:latest
    container_name: frontendBlue
    restart: always
    expose:
      - "80"
    depends_on:
      backend-blue:
        condition: service_healthy
    networks:
      - panne-jirama-blue

volumes:
  django_static:
    external: true
    name: jirama-django-static
  django_media:
    external: true
    name: jirama-django-media

networks:
  panne-jirama-blue :
    external: true
    name: panne-jirama-blue        