services:
  db:
    image: mysql:8.0
    container_name: db-staging
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 40s
    volumes:
      - mysql_data_staging:/var/lib/mysql
    networks:
      - panne_jirama_staging

  backend:
    image: zomahefaranaivo/django-backend-panne-staging:v8
    container_name: backend-staging
    restart: always
    environment:
      APP_ENV: ${APP_ENV}
      DEBUG: ${DEBUG}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    volumes:
      - django_static:/back/staticfiles
      - django_media:/back/media
    depends_on:
      db:
        condition: service_healthy
    networks:
      - panne_jirama_staging

  frontend:
    image: zomahefaranaivo/react-frontend-nginx-panne-staging:v8
    container_name: frontend-staging
    restart: always
    ports:
      - 80:80
    volumes:
      - django_static:/back/staticfiles
      - django_media:/back/media
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - panne_jirama_staging

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - panne_jirama_staging
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"  # On expose Grafana sur le port 3001
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - panne_jirama_staging
  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - panne_jirama_staging

  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - ./monitoring/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - panne_jirama_staging

volumes:
  mysql_data_staging:
  django_static:
  django_media:
  grafana_data:
    external: true
    name: gestion-de-panne-devops_grafana_data

networks:
  panne_jirama_staging:
