services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus-monitoring
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=https://signaler-panne-305.duckdns.org/prometheus/'
      - '--web.route-prefix=/prometheus'
    depends_on:
      - mysql-exporter
    networks:
      - panne-jirama-blue
      - panne-jirama-green 
  grafana:
    image: grafana/grafana
    container_name: grafana-monitoring
    environment:
      - GF_SERVER_ROOT_URL=https://signaler-panne-305.duckdns.org/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
    networks:
      - panne-jirama-blue
      - panne-jirama-green 
  loki:
    image: grafana/loki:2.9.4
    container_name: loki-monitoring
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - panne-jirama-blue
      - panne-jirama-green 
  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail-monitoring
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - ./monitoring/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - panne-jirama-blue
      - panne-jirama-green 
  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysql-exporter-monitoring
    restart: always
    command:
      - '--config.my-cnf=/etc/.my.cnf'
    volumes:
      - ./.my.cnf:/etc/.my.cnf:ro
    networks:
      - panne-jirama-blue
      - panne-jirama-green 
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter-monitoring
    ports:
      - "9100:9100"
    networks:
      - panne-jirama-blue
      - panne-jirama-green


volumes:
  grafana_data:
    external: true
    name: grafana-data-jirama

networks:
  panne-jirama-blue:
    external: true
    name: panne-jirama-blue  
  panne-jirama-green:
    external: true
    name: panne-jirama-green           