events {}

http {
  include       mime.types;
  default_type  application/octet-stream;

  server {
    listen 80;
    server_name signaler-panne-305.duckdns.org;
    return 301 https://$host$request_uri;
  }

  server {
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    listen 443 ssl;
    server_name signaler-panne-305.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/signaler-panne-305.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/signaler-panne-305.duckdns.org/privkey.pem;

    resolver 127.0.0.11 ipv6=off;

    # Définition des upstreams avec include
    upstream frontend {
      include /etc/nginx/conf.d/frontend_active.conf;
    }

    upstream backend {
      include /etc/nginx/conf.d/backend_active.conf;
    }

    location / {
      proxy_pass http://frontend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_redirect off;
      proxy_intercept_errors on;
      error_page 404 = /index.html;
    }

    location ~ ^/api(/|$) {
      proxy_pass http://backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_redirect off;
    }

    location /django-static/ {
      alias /back/staticfiles/;
      access_log off;
      expires 30d;
      add_header Cache-Control "public";
    }

    location /media/ {
      alias /back/media/;
      access_log off;
      expires 30d;
      add_header Cache-Control "public";
    }

    location ~ ^/grafana(/|$) {
      proxy_pass http://grafana:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_redirect off;
    }

    location ~ ^/prometheus(/|$) {
      proxy_pass http://prometheus:9090;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_redirect off;
    }

    location = /metrics/ {
      proxy_pass http://backend;
      proxy_set_header Host localhost;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_redirect off;
    }

    location = /mysql-metrics/ {
      proxy_pass http://mysql-exporter:9104/metrics;
      proxy_set_header Host localhost;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_redirect off;
    }
  }
}
