global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django-backend'
    metrics_path: /metrics/
    scheme: https
    static_configs:
      - targets: ['signaler-panne-305.duckdns.org']
        labels:
          color: active
          instance: backend
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: instance
        replacement: backend

  - job_name: 'mysql'
    metrics_path: /mysql-metrics/
    scheme: https
    static_configs:
      - targets: ['signaler-panne-305.duckdns.org']
        labels:
          color: active
          instance: mysql

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          color: host
          instance: node
