global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django-backend'
    metrics_path: /metrics/
    scheme: https
    static_configs:
      - targets: ['signaler-panne-305.duckdns.org']
    relabel_configs:
      - target_label: instance
        replacement: backend   # 🏷️ Remplace l'instance (qui serait le nom de domaine) par "backend"
      - target_label: color
        replacement: active 

  - job_name: 'mysql'
    metrics_path: /metrics
    static_configs:
      - targets: ['mysql-exporter:9104']
    relabel_configs:
      - target_label: instance
        replacement: mysql

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - target_label: instance
        replacement: serveur
      - target_label: color
        replacement: host

  - job_name: 'cadvisor'
    metrics_path: /metrics
    static_configs:
      - targets: ['cadvisor:8080']
    relabel_configs:
      - source_labels: [container_label_com_docker_compose_service]
        target_label: service
      - source_labels: [container_label_com_docker_compose_project]
        target_label: project
      - source_labels: [container_label_com_docker_compose_container_number]
        target_label: container_number
      - target_label: instance
        replacement: cadvisor

